{
 "title": "MyDash",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU-USER",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{instance=\"app:3010\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU-SYSTEM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total{instance=\"app:3010\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"app:3010\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PROCESS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"app:3010\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HANDLES",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=\"app:3010\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL REQUESTS - ROUTE /POSTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{instance=\"app:3010\", route=\"/posts\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESPONSE TIME - ROUTE /POSTS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{route=\"/posts\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL REQUESTS - ROUTE /POSTS/SEARCH",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{instance=\"app:3010\", route=\"/posts/search\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL REQUESTS - ROUTE /POSTS/:postId",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{instance=\"app:3010\", route=\"/posts/:postId\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}